import requests
import json

BASE = "http://localhost:8080/api/v1"

print("=== 1. Testing Login ===")
r_login = requests.post(f"{BASE}/auth/login", json={"username": "officer@nic.in", "password": "Sentinel@2026"})
print("Login status:", r_login.status_code)
token = r_login.json().get("token")
print("User:", r_login.json().get("fullName"), "| Role:", r_login.json().get("role"))

headers = {"Authorization": f"Bearer {token}"}

print("\n=== 2. Testing Project List ===")
r_proj = requests.get(f"{BASE}/projects?page=0&size=3", headers=headers)
print("Projects count:", r_proj.json().get("totalElements"))
for p in r_proj.json().get("content", []):
    print(f" - {p['projectId']}: {p['projectName']} [{p['riskLevel']} - {p['riskScore']}]")

print("\n=== 3. Testing Project Details (MPL-10482) ===")
r_det = requests.get(f"{BASE}/projects/MPL-10482", headers=headers)
p_det = r_det.json()
print("Details:", p_det["projectId"], p_det["projectName"])
print(f"Sanctioned: Rs. {p_det['sanctionedAmount']}, Expenditure: Rs. {p_det['expenditureAmount']}, Progress: {p_det['progressPercentage']}%")

print("\n=== 4. Testing Live Pipeline Analysis (POST /analyze) ===")
r_ana = requests.post(f"{BASE}/projects/MPL-10482/analyze", headers=headers)
ana = r_ana.json()
print("Analysis Status:", r_ana.status_code)
print(f"Calculated Risk Score: {ana['riskScore']} / 100 ({ana['riskLevel']})")
print(f"Investigation Priority: {ana['investigationPriority']}")
print("Factors flagged:")
for f in ana.get("factors", []):
    print(f" - [{f['type']} | {f['severity']}]: {f['explanation']}")

print("\n=== 5. Testing Nearby GIS Projects ===")
r_near = requests.get(f"{BASE}/projects/nearby?projectId=MPL-10482&radiusKm=5.0", headers=headers)
near = r_near.json()
np_list = near.get("nearbyProjects", [])
print(f"Found {len(np_list)} nearby projects:")
for np in np_list:
    print(f" - {np['projectId']} ({np['distanceKm']} km): {np['projectName']} [Overlap: {np['potentialOverlap']}]")

print("\n=== 6. Testing Investigation Report Generation ===")
r_rep = requests.post(f"{BASE}/reports/MPL-10482", headers=headers)
rep = r_rep.json()
print("Report ID:", rep.get("reportId"))
print("Generated By:", rep.get("generatedBy"))
print("Disclaimer:", rep.get("disclaimer"))